import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { ReduxProvider } from "./redux/Provider";

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-ubuntu",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased dark font-quickSand ${ubuntu.className} `}>
        <ReduxProvider>
          {" "}
          <NavBar></NavBar>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
